/*
 * syscall_numbers.h
 *
 *  Created on: 17.06.2017
 *      Author: pascal
 */

#ifndef BITS_SYSCALL_NUMBERS_H_
#define BITS_SYSCALL_NUMBERS_H_

enum{
SYSCALL_ALLOC_PAGES		= 0,
SYSCALL_FREE_PAGES		= 1,
SYSCALL_UNUSE_PAGES		= 2,

SYSCALL_EXEC			= 10,
SYSCALL_EXIT			= 11,
SYSCALL_WAIT			= 12,
SYSCALL_THREAD_CREATE	= 13,
SYSCALL_THREAD_EXIT		= 14,

SYSCALL_OPEN			= 40,
SYSCALL_CLOSE			= 41,
SYSCALL_READ			= 42,
SYSCALL_WRITE			= 43,
SYSCALL_INFO_GET		= 44,
SYSCALL_INFO_SET		= 45,
SYSCALL_MKDIR			= 46,

SYSCALL_MOUNT			= 50,
SYSCALL_UNMOUNT			= 51,

SYSCALL_GET_TIMESTAMP	= 50,
SYSCALL_SLEEP			= 51,

SYSCALL_SYSINF_GET		= 60,

_SYSCALL_NUM
};

#endif /* BITS_SYSCALL_NUMBERS_H_ */
